version: '3.6'

services:
  alpine-apache2-reverse-proxy-hl:
    build: .
    image: hackinglab/alpine-apache2-reverse-proxy-hl:3.2
    environment:
      - "HL_USER_USERNAME=hacker"
      - "HL_USER_PASSWORD=compass"
    ports:
      - 80:80
      - 443:443
