#!/command/with-contenv bash

echo "testing apache2 backend config"
/usr/sbin/httpd -f /etc/apache2/httpd-backend.conf -t; 

echo "starting apache2-backend"
exec /usr/sbin/httpd -f /etc/apache2/httpd-backend.conf -k start -DFOREGROUND;

